import React from 'react';
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
export default function ResultsPanel({result}){
 const o=result.optimized,b=result.baseline,f=result.fleet_plan;
 const fuelPerTonne=o.fuel_litres/Math.max(result.route?.cargo_tonnes||f.cargo_tonnes,1);
 const penaltyLitres=(result.segment_penalties||[]).reduce((a,x)=>a+(x.penalty?.fuel_penalty_litres||0),0);
 return <div className="grid-3">
  <section className="card"><h3>Fuel consumption</h3><div className="metric"><b>{fmt(o.fuel_litres)} L</b><span>ML-predicted fuel</span></div><div className="metric"><b>{fmt(fuelPerTonne)}</b><span>Litres / cargo tonne</span></div><div className="metric"><b>{fmt(o.fuel_cost)}</b><span>Fuel cost index</span></div><p>Fuel: <strong>{o.fuel_type}</strong> · Speed: <strong>{o.speed_knots} kn</strong> {result.voyage_parameters ? `(Range: ${result.voyage_parameters.speed_min_knots}–${result.voyage_parameters.speed_max_knots} kn)` : ''} · ETA: <strong>{o.eta_hours} h</strong> {result.voyage_parameters?.schedule_window_hours ? `(Window: ±${result.voyage_parameters.schedule_window_hours} h)` : ''}</p></section>
  <section className="card"><h3>Fuel & emissions comparison</h3><div className="metric"><b>{fmt(b.fuel_litres)} L</b><span>Baseline ({b.fuel_type})</span></div><div className="metric"><b>{result.savings.fuel_percent}%</b><span>{result.savings.label || 'Fuel vs baseline'}</span></div><div className="metric"><b>{fmt(o.co2_kg)} kg</b><span>Operational CO₂</span></div><p>QPSO searches speed + fuel together using the same fuel-aware ML predictor.</p></section>
  <section className="card"><h3>Environmental exposure</h3><div className="metric"><b>{result.avg_environmental_score}</b><span>Average marine score / 100</span></div><div className="metric"><b>{fmt(penaltyLitres)} L</b><span>Mapped segment penalty exposure</span></div><div className="metric"><b>{result.route.distance_km.toLocaleString()} km</b><span>Selected route distance</span></div><p>Heat-map penalties are shown separately from the ML fuel prediction to avoid double-counting them.</p></section>
  <section className="card wide"><h3>Cargo allocation</h3><div className="metric"><b>{f.fleet_count}</b><span>Ships selected</span></div><div className="metric"><b>{f.capacity_utilization_percent}%</b><span>Capacity utilized</span></div><div className="metric"><b>{f.unused_capacity_tonnes.toLocaleString()} t</b><span>Unused capacity</span></div><p>{f.cargo_tonnes.toLocaleString()} t demand is fully allocated.</p></section>
  <section className="card wide"><h3>Ship-by-ship cargo split</h3><div className="table"><div className="tr head"><span>Ship</span><span>Type</span><span>Cargo</span><span>Capacity</span><span>Utilization</span><span>Fuel</span></div>{f.ships.map(s=><div className="tr" key={s.ship_no}><span>#{s.ship_no}</span><span>{s.fleet_type}</span><span>{s.cargo_tonnes.toLocaleString()} t</span><span>{s.capacity_tonnes.toLocaleString()} t</span><span>{s.utilization_percent}%</span><span>{s.fuel_litres.toLocaleString()} L</span></div>)}</div></section>
 </div>
}
